#!/bin/bash

# ==============================================================================
# Script Name: install_docker.sh
# Description: This script installs Docker CE (Community Edition), Docker Compose,
#              and related tools on a CentOS 9 Stream system.
# Author:      FantasticTony (Generated by AI Assistant)
# Version:     1.0
# Date:        06-04-2025
# ==============================================================================

# Source utility functions
UTILS_PATH="$(dirname "$0")/utils.sh"
if [ ! -f "${UTILS_PATH}" ]; then
    echo -e "\033[0;31m[ERROR] utils.sh not found at ${UTILS_PATH}. Please ensure it's in the same directory as this script.\033[0m"
    exit 1
fi
source "${UTILS_PATH}"

# --- Script Start ---
# The msg_info from utils.sh will confirm it's loaded.
msg_info "Starting Docker CE installation script..."

# Check if Docker is already installed
if command -v docker &> /dev/null; then
    msg_warning "Docker appears to be already installed."
    docker --version
    read -p "Do you want to proceed with reinstallation? (y/N): " CONFIRM_REINSTALL
    if [[ ! "$CONFIRM_REINSTALL" =~ ^[yY](es)?$ ]]; then
        msg_info "Exiting script as per user request."
        exit 0
    fi
    msg_info "Proceeding with Docker reinstallation..."
fi

# --- Remove Old Docker Versions ---
msg_info "Removing any old Docker versions..."
dnf remove docker \
                  docker-client \
                  docker-client-latest \
                  docker-common \
                  docker-latest \
                  docker-latest-logrotate \
                  docker-logrotate \
                  docker-engine -y &> /dev/null
# We don't use check_exit_status here as 'dnf remove' exits with 1 if packages are not found.
# A success message is sufficient as it's a cleanup step.
msg_success "Finished attempting to remove old Docker versions. It's okay if some packages were not found."

# --- Setup Docker Repository ---
msg_info "Setting up Docker CE repository..."
dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
check_exit_status "Failed to add Docker CE repository." "Docker CE repository added successfully."

msg_info "Making DNF cache..."
dnf makecache
check_exit_status "Failed to make DNF cache." "DNF cache updated successfully."

# --- Install Docker Packages ---
msg_info "Installing Docker CE, CLI, containerd, and plugins..."
# Package names for CentOS 9 Stream should be current as per Docker's official documentation.
dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
check_exit_status "Failed to install Docker packages." "Docker CE and related packages installed successfully."

# --- Start and Enable Docker Service ---
msg_info "Starting Docker service..."
systemctl start docker
check_exit_status "Failed to start Docker service." "Docker service started successfully."

msg_info "Enabling Docker service to start on boot..."
systemctl enable docker
check_exit_status "Failed to enable Docker service." "Docker service enabled successfully."

# --- Verify Installation ---
msg_info "Verifying Docker installation..."
if command -v docker &> /dev/null; then
    docker --version
    msg_success "Docker installed and version verified."
    msg_info "Attempting to run hello-world container..."
    docker run hello-world
    if [ $? -ne 0 ]; then
        msg_warning "Docker hello-world container failed to run. Docker might be installed but not working correctly."
    else
        msg_success "Docker hello-world container ran successfully."
    fi
else
    msg_error "Docker command not found after installation. Installation may have failed."
    exit 1
fi

msg_success "===== Docker CE Installation Complete! ====="
msg_info "You may need to add your user to the 'docker' group to run Docker commands without sudo:"
msg_info "sudo usermod -aG docker \${USER}"
msg_info "After running this command, you will need to log out and log back in for the changes to take effect."

exit 0
